services:
  chess-backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - OTEL_SERVICE_NAME=chess-engine-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SIGNOZ_UI_URL=http://localhost:3301
    depends_on:
      - otel-collector

  chess-frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - chess-backend

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
